### PR TITLE
A few minor fixes

### LINKED ISSUE #45: Configuration.GetBaseAddress() does return correct address when BasePath is set
this logic needs flipping round ... 
https://github.com/ScottLogic/openapi-forge-csharp/blob/master/template/Configuration.cs.handlebars#L19-L26

need to build the URL from BasePath then Server

### PR DESCRIPTION
**Pull request by ColinEberhardt**
see commit messages for details

fixes #45

### CODE REVIEW

File: template/Configuration.cs.handlebars [hunk 1]
```diff
@@ -16,23 +16,9 @@ using System.Text;
...
-        return RemoveTrailingSlash(sb).ToString();
-    }
-
-    private static StringBuilder RemoveTrailingSlash(StringBuilder sb)
-    {
-        return sb.Length > 0 && sb[sb.Length - 1] == '/'
-            ? sb.Remove(sb.Length - 1, 1)
-            : sb;
+        var sb = new StringBuilder(BasePath);
+        sb.Append(Servers[SelectedServerIndex]);
```
Comment (ColinEberhardt) [inline template/Configuration.cs.handlebars:20]: NOTE: This aligns with the JS / TS implementations that just concatenate the strings:

https://github.com/ScottLogic/openapi-forge-javascript/blob/main/template/request.js#L11

**Review by murcikan-scottlogic — APPROVED** [review]

**Review by murcikan-scottlogic — APPROVED** [review]
